config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'recipes#index'

  resources :recipes, only: [:index, :show] do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :bigint           not null, primary key
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  recipe_id   :bigint
#
# Indexes
#
#  index_ingredients_on_recipe_id  (recipe_id)
#
# Foreign Keys
#
#  fk_rails_...  (recipe_id => recipes.id)
#
class Ingredient < ApplicationRecord
  belongs_to :recipe

  # TODO: find a way to parse description
  # to distinguish quantity and actual ingredient
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id              :bigint           not null, primary key
#  author          :string
#  author_tip      :string
#  budget          :string
#  cook_time       :string
#  difficulty      :string
#  image           :string
#  name            :string
#  people_quantity :string
#  prep_time       :string
#  rate            :string
#  total_time      :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Recipe < ApplicationRecord
  has_and_belongs_to_many :tags
  has_many :ingredients

  # returns recipes ordered by percent of ingredients matching search_string
  # TODO: either use a search by ingredient id (if we find a way to parse them)
  # Or do a better search for full words (maybe use elasticsearch?)
  # TODO: add ingredients_count in recipes so we don't need to use subquery for total_count
  # TODO: list ingredients that everyone owns (salt, pepper...), ignore those in search
  def self.find_by_ingredients(search_string)
    return all unless search_string.present?

    # We remove any char not in French dictionary
    words_for_query = connection.quote(
      search_string.gsub(/[^a-zàâçéèêëîïôûùüÿñæœ ]/i, '').split(' ').join(' | ')
    )

    query = <<-SQL
      SELECT *,
             CASE
               WHEN total_count = 0 THEN 0
               ELSE round(100 * (1 - missing_count::decimal / total_count), 2)
             END AS percent_match
      FROM(
        SELECT *,
               (
                 SELECT COUNT(*)
                 FROM ingredients
                 WHERE ingredients.recipe_id = recipes.id
                   AND NOT to_tsvector(ingredients.description) @@ to_tsquery(#{words_for_query})
               ) AS missing_count,
               (
                 SELECT COUNT(*)
                 FROM ingredients
                 WHERE ingredients.recipe_id = recipes.id
               ) AS total_count
        FROM recipes
      ) sub
      ORDER BY percent_match DESC
    SQL

    select('*').from("(#{query}) AS recipes")
  end

  def as_json(*)
    super.slice('name', 'image', 'total_time').tap do |hash|
      hash['show_path'] = Rails.application.routes.url_helpers.recipe_path(self)

      # If the recipe was retrieved with find_by_ingredients, percent_match will be filled
      hash['percent_match'] = self.try(:percent_match)
    end
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Tag < ApplicationRecord
  has_and_belongs_to_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: :show

  def index; end

  def search
    render json: Recipe.find_by_ingredients(params[:search_text]).limit(30)
  end

  def show; end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    head :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script><%= yield :page_scripts %></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<%= form_with(url: search_recipes_path(format: :json), method: :get, id: 'recipes_search') do |f| %>
  <%=
    f.label(
      :search_text,
      'De quels ingrédients disposez-vous? (Séparez les ingrédients par un espace)'
    )
  %>
  <br/>
  <%= f.text_area :search_text %>
  <br/>
  <%= f.submit 'Search' %>
<% end %>

<table>
  <thead>
  <tr>
    <th>name</th>
    <th>total_time</th>
    <th>% match</th>
  </tr>
  </thead>
  <tbody id="recipes_tbody">
  </tbody>
</table>

<% content_for :page_scripts do %>
  $(document).ready(function() {
    addRecipeSearchListeners();
  });
<% end %>

app/views/recipes/show.html.erb
<div>
  <h1><%= @recipe.name %></h1>
</div>

<div>
  Ingrédients:
  <ul>
    <% @recipe.ingredients.each do |ingredient| %>
      <li><%= ingredient.description %></li>
    <% end %>
  </ul>
</div>